version: '3.5'

services:
  backend:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/app
  frontend:
    # build: movie_page_test/.
    build:
      context: movie_page_test/.
      dockerfile: Dockerfile
    # command: sh -c "npm run dev"
    ports:
      - '3000:3000'
    volumes:
      - ./movie_page_test:/app
      - /app/node_modules
    #   - /app/node_modules